# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e1eb587ce774d6d099c4f78e993003241d2660586fb51024f1a5265cdf4fa9f11a2995dbb883524f13b45fe6584576e77c57a29bff01feefea00af96c67cc9a

test:
  secret_key_base: e6a238b463d10a86bedbe8c4b4e78f0c1847fdc6cd6304688bae5275e0c8a21dfd086a2ff8cf9309c81b23ed0e45844467d49fb936cc132e8125100bd84db730

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
